# Introduction to Pytorch
This notebook will provide a brief overview of PyTorch and how it is similar to Numpy. The goal of this notebook is to understand the basic data structures required to build Deep Learning models and train them.

Why do we need PyTorch when we already have Numpy?
Deep Learning involves performing similar operations like convolutions and multiplications repetitively. Thus there is a need to run the code on GPUs which can parallelize these operations over multiple cores - these devices are perfectly suitable for doing massive matrix operations and are much faster than CPUs.

In [1]:
import numpy as np
import torch

While NumPy with its various backends suits perfectly for doing calculus on CPU, it lacks the GPU computations support. And this is the first reason why we need Pytorch.

The other reason is that Numpy is a genral purpose library. PyTorch ( or any other modern deep learning library ) has optimized code for many deep learning specific operations (e.g. Gradient calculations ) which are not present in Numpy.

So, let's take a look at what are the data structures of Pytorch and how it provides us its cool features.

# Tensor Creation

2 dimensional (rank2 tensor of zeros)

In [2]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Random rank -4 Tensor

In [3]:
torch.rand(2,2,2,2)

tensor([[[[0.6465, 0.9161],
          [0.3537, 0.0972]],

         [[0.3524, 0.7389],
          [0.6831, 0.7920]]],


        [[[0.2586, 0.4030],
          [0.2282, 0.4832]],

         [[0.4378, 0.2899],
          [0.7514, 0.9135]]]])

# Python/Numpy/Pytorch interoperability

In [ ]:
#Simple List
Python_list = [1,2]

#create a numpy array from the python list
numpy_array = np.array(Python_list)

#create a torch tensor from the python list
tensor_from_list = torch.tensor(Python_list)

#create a torch Tensor from the numpy array
tensor_from_numpy = torch.tensor(numpy_array)

#aNOTHER WAY TO CREATE A TENSOR FROM A NUMPY ARRAY
tensor_from_numpy_v2 = torch.from_numpy(numpy_array)

#Convert torch tensor to numpy array
array_from_tensor = tensor_from_numpy.numpy()

print("Python List: ", Python_list)
print("Numpy Array: ", numpy_array)
print("Torch Tensor from List: ", tensor_from_list)
print("Torch Tensor from Numpy Array: ", tensor_from_numpy)
print("Torch Tensor from Numpy Array v2: ", tensor_from_numpy_v2)
print("Numpy Array from Torch Tensor: ", array_from_tensor)

Python List:  [1, 2]
Numpy Array:  [1 2]
Torch Tensor from List:  tensor([1, 2])
Torch Tensor from Numpy Array:  tensor([1, 2], dtype=torch.int32)
Torch Tensor from Numpy Array v2:  tensor([1, 2], dtype=torch.int32)
Numpy Array from Torch Tensor:  [1 2]


# Difference between torch.Tensor and torch.from_numpy
Pytorch aims to be effective library for computations. what does it mean? it means that pytorch avoids memory copying if it can:

In [7]:
numpy_array[0] = 10

print('Array: ', numpy_array)
print('Tensor', tensor_from_numpy)
print('Tensor v2', tensor_from_numpy_v2)


Array:  [10  2]
Tensor tensor([1, 2], dtype=torch.int32)
Tensor v2 tensor([10,  2], dtype=torch.int32)


So, we have two different ways to create tensor from its Numpy counterpart- one copies memory and another shares the same underlying storage.It also works in the opposite way

In [8]:
array_from_tensor = tensor_from_numpy.numpy()
print('Tensor:', tensor_from_numpy)
print('Array:', array_from_tensor)

tensor_from_numpy[0]= 11
print('Tensor:', tensor_from_numpy)
print('Array:', array_from_tensor)

Tensor: tensor([1, 2], dtype=torch.int32)
Array: [1 2]
Tensor: tensor([11,  2], dtype=torch.int32)
Array: [11  2]


# Data Types

In [9]:
tensor = torch.zeros(2,2)
print('Tensor with default type:', tensor)
tensor = torch.zeros(2,2, dtype=torch.float16)
print('Tensor with float16 type:', tensor)
tensor = torch.zeros(2,2, dtype=torch.int16)
print('Tensor with int16 type:', tensor)
tensor = torch.zeros(2,2, dtype=torch.bool)
print('Tensor with bool type:', tensor)

Tensor with default type: tensor([[0., 0.],
        [0., 0.]])
Tensor with float16 type: tensor([[0., 0.],
        [0., 0.]], dtype=torch.float16)
Tensor with int16 type: tensor([[0, 0],
        [0, 0]], dtype=torch.int16)
Tensor with bool type: tensor([[False, False],
        [False, False]])


# Indexing

Joining a list of tensors with torch.cat

In [10]:
a = torch.zeros(3,2)
b = torch.zeros(3,2)
print(torch.cat((a,b), dim=0))
print(torch.cat((a,b), dim=1))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
a = torch.arange(start=0, end = 10)
indices = np.arange(0,10)>5
print(a)
print(indices)
print(a[indices])

indices = torch.arange(start=0, end = 10)%5
print(indices)
print(a[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[False False False False False False  True  True  True  True]
tensor([6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])


what should we do if we havbe say rank2 tensor and want to select only some rows?

In [13]:
tensor = torch.rand((5,3))
rows = torch.tensor([0,2,4])
print(tensor)
print(tensor[rows])

tensor([[0.6064, 0.2400, 0.6771],
        [0.8170, 0.3314, 0.4365],
        [0.4307, 0.5481, 0.0615],
        [0.7245, 0.5518, 0.4984],
        [0.8665, 0.3314, 0.9460]])
tensor([[0.6064, 0.2400, 0.6771],
        [0.4307, 0.5481, 0.0615],
        [0.8665, 0.3314, 0.9460]])


# Tensor Shapes

Reshaping a tensor is a frequently used operation. We can change the shape of a tensor without the memory copying overhead. There are two methods for that: reshape and view.

The difference is the following:

view tries to return the tensor, and it shares the same memory with the original tensor. In case, if it cannot reuse the same memory due to some reasons, it just fails.
reshape always returns the tensor with the desired shape and tries to reuse the memory. If it cannot, it creates a copy.
Let's see with the help of an example

In [20]:
tensor = torch.rand(2,3,4)
print('Pointer to data:', tensor.data_ptr())
print('Shape:', tensor.shape)

reshaped = tensor.reshape(24)

view = tensor.view(3,2,4)
print('Reshaped tensor - pointer to data:', reshaped.data_ptr())
print('Reshaped tensor - shape:', reshaped.shape)

print('View tensor - pointer to data:', view.data_ptr())
print('View tensor - shape:', view.shape)

assert tensor.data_ptr() == view.data_ptr(), 'View and original tensor do not share the same data!'

assert np.all(np.equal(tensor.numpy().flat, reshaped.numpy().flat))

print('Original stride: ', tensor.stride())
print('Reshaped stride: ', reshaped.stride())
print('Viewed stride: ', view.stride())

Pointer to data: 5124210689792
Shape: torch.Size([2, 3, 4])
Reshaped tensor - pointer to data: 5124210689792
Reshaped tensor - shape: torch.Size([24])
View tensor - pointer to data: 5124210689792
View tensor - shape: torch.Size([3, 2, 4])
Original stride:  (12, 4, 1)
Reshaped stride:  (1,)
Viewed stride:  (8, 4, 1)


The basic rule about reshaping the tensor is definitely that you cannot change the total number of elements in it, so the product of all tensor's dimensions should always be the same. It gives us the ability to avoid specifying one dimension when reshaping the tensor - Pytorch can calculate it for us:

In [21]:
print(tensor.reshape(3, 2, 4).shape)
print(tensor.reshape(3, 2, -1).shape)
print(tensor.reshape(3, -1, 4).shape)

torch.Size([3, 2, 4])
torch.Size([3, 2, 4])
torch.Size([3, 2, 4])


Alternative ways to view tensors - expand or expand_as.

expand - requires the desired shape as an input
expand_as - uses the shape of another tensor.
These operaitions "repeat" tensor's values along the specified axes without actual copying the data.

As the documentation says, expand

returns a new view of the self tensor with singleton dimensions expanded to a larger size. Tensor can be also expanded to a larger number of dimensions, and the new ones will be appended at the front. For the new dimensions, the size cannot be set to -1.

Use case:

index multi-channel tensor with single-channel mask - imagine a color image with 3 channels (R, G and B) and binary mask for the area of interest on that image. We cannot index the image with this kind of mask directly since the dimensions are different, but we can use expand_as operation to create a view of the mask that has the same dimensions as the image we want to apply it to, but has not copied the da

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

#Create a black image
image = torch.zeros(size=(3, 256, 256), dtype=torch.int)

#Leave the borders and make the rest of the image Green
image[1, 18:256 - 18, 18:256 - 18] = 255

#Create a mask of the same size
mask = torch.zeros(size=(256, 256), dtype=torch.bool)

#Assuming the green area in the original image is the area of interest, change the mask to white for that area
mask[18:256 - 18, 18:256 - 18] = 1

In [ ]:
# Expand the mask to have the same dimensions as the image
expanded_mask = mask.unsqueeze(0).expand_as(image)
print('Mask shape:', mask.shape)
print('Expanded mask shape:', expanded_mask.shape)
print('Image shape:', image.shape)

In [ ]:
# Apply the mask to the image
# Only keep pixels where mask is True
masked_image = image.clone()
masked_image[~expanded_mask] = 0

# Visualize the results
plt.figure(figsize=(15, 5))

plt.subplot(131)
plt.title('Original Image')
plt.imshow(image.permute(1, 2, 0).numpy())

plt.subplot(132)
plt.title('Mask')
plt.imshow(mask.numpy(), cmap='gray')

plt.subplot(133)
plt.title('Masked Image')
plt.imshow(masked_image.permute(1, 2, 0).numpy())

plt.tight_layout()
plt.show()